// This file is autogenerated in the Unity Editor, by BundleVersionChecker
public static class CurrentBundleVersion
{
	public static readonly string Version = "1.3";
	public static readonly string BuildDate = "2018-05-20";
}

