// This file is autogenerated in the Unity Editor, by BundleVersionChecker
public static class CurrentBundleVersion
{
	public static readonly string Version = "2.0";
	public static readonly string BuildDate = "2018-06-16";
}

